### PR TITLE
pass options to spawn

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Thanks for the lib. It would be nice to pass options to the spawn protractor process (e.g. to change cwd).

### CODE REVIEW

**Comment by NickTomlin** [comment]
This is great!

Could you add a test documenting this behaviour? A new `it` block to the [index.test.js](https://github.com/NickTomlin/protractor-flake/blob/master/test/index.test.js#L35) using spawnStub would be a good start. 

Also, we should support this via the [executable](https://github.com/NickTomlin/protractor-flake/blob/master/bin/protractor-flake#L3). I'm not sure if [minimist](https://github.com/NickTomlin/protractor-flake/blob/master/bin/protractor-flake#L3) support sub arguments by default, but perhaps a syntax like this would work? 

``` shell
protractor-flake --protractorSpawnArgs [ --cwd '/my/path' ]
```

**Comment by donaldpipowitch** [comment]
I don't know if there is a use case for setting this via executable. In my project I just spawn protractor-flake with a different cwd so protractor automatically gets the cwd protractor-flake uses. The spawn options are basically inherited.

I can try to add a test later this week for the programmatic API.

**Comment by NickTomlin** [comment]
@donaldpipowitch I guess that's fair. We can always back port it later. I just want to make sure things don't get too out of sync between the too. 

Later this week sounds great; let me know if you need any assistance. Thanks!

**Comment by donaldpipowitch** [comment]
Does that work for you?

**Comment by NickTomlin** [comment]
This looks great! If it's not too much trouble, could you squash it all into one commit? After that i'll merge and publish a new version. Thanks again!

**Comment by donaldpipowitch** [comment]
Yeah. I can do that in a few days ^^° I'm currently mobile only.

**Comment by NickTomlin** [comment]
That's fine :)

**Pull request closed without merging**
