### PR TITLE
Add support for parsing cucumberjs output

### PR DESCRIPTION
**Pull request by jrust**
Adds support for [cucumber-js](https://github.com/cucumber/cucumber-js) output.  Tested against protractor running cucumber-js and chai and flake worked great.

### CODE REVIEW

**Comment by NickTomlin** [comment]
This is great. Thanks!

**Comment by jrust** [comment]
Thanks for merging! Am I wrong in thinking semantic-release should have auto-created a release?  If it is supposed to, I haven't seen it show up yet on the npm servers.

**Comment by NickTomlin** [comment]
@jrust it should have but I just realized that your commit message won't be parsed by semantic-release. That is my fault for not updating the contributor guidelines. I'll bump now. Sorry for the delay!

**Comment by NickTomlin** [comment]
Looks like the bump did not work. I'm going to look into this.

**Comment by NickTomlin** [comment]
Okay it's finally out as `0.5.1` it really should be `0.6.0` but it felt weird adding an empty `major` commit to the chain. I'm still getting the hang of semantic release :)

**Comment by jrust** [comment]
Cool, thanks for looking into it.

**Comment by wswebcreation** [comment]
@jrust,

Which version of cucumber did you use for this parser? I'm using 0.10.4 and I get this for failed scenario's. This means that the selector in the cucumber parser `/(.*?):\d+ # Scenario:.*/g` doesn't work

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Feature: Failing stuff

  Scenario: Flakey scenario
    Then it fails in a consistent manner

Failures:

1) Scenario: Flakey scenario - test/e2e/features/functional/flakey.feature:15
   Step: Then it fails in a consistent manner - test/e2e/features/functional/flakey.feature:8
   Step Definition: test/flakey.steps.js:19
   Message:
     flakey error was thrown

1 scenario (1 failed)
1 step (1 failed)
0m00.332s
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
>>
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
```

**Pull request merged**
